onboarding = false

[keys]
prefix = "ctrl+s"
split_vertical = "prefix+shift+backslash"
split_horizontal = "prefix+minus"

[ui]
prompt_new_tab_name = false
prompt_new_workspace_name = false

[ui.sound]
enabled = false
