onboarding = false

[keys]
prefix = "ctrl+s"
split_vertical = "prefix+="
split_horizontal = "prefix+minus"
close_pane = "ctrl+x"
new_workspace = "prefix+shift+c"

[ui]
prompt_new_tab_name = false
prompt_new_workspace_name = true

[ui.sound]
enabled = false

[theme]
name = "vesper"
auto_switch = false
