onboarding = false

[keys]
prefix = "ctrl+s"
split_vertical = "prefix+="
split_horizontal = "prefix+minus"
close_pane = "ctrl+x"

[ui]
prompt_new_tab_name = false
prompt_new_workspace_name = false

[ui.sound]
enabled = false

[theme]
name = "rose-pine"
auto_switch = false
