address=/cloudflared.home/10.0.0.100
address=/tunnel.home/10.0.0.100
address=/ollama.home/10.0.0.100
address=/open-webui.home/10.0.0.100
address=/webui.home/10.0.0.100
address=/navidrome.home/10.0.0.100
address=/openspeedtest.home/10.0.0.100
address=/speedtest.home/10.0.0.100

server=1.1.1.1
server=8.8.8.8

log-queries
