# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-tmux */

# Panes borders
set -g pane-border-style 'fg=#444444 bg=#262626'
set -g pane-active-border-style 'fg=#5F8787 bg=#262626'

# Status bar - match terminal background
set -g status-justify left
set -g status-style 'fg=#6C6C6C bg=#262626'
set -g status-left '#[fg=#87875F,bold][ #S ]'
set -g status-left-length 15
set -g status-right-style 'fg=#5F8787 bg=#262626'

# Window status - current window is DARK/DIM, other windows are bright
setw -g window-status-current-style 'fg=#444444 bg=#262626 dim'
setw -g window-status-style 'fg=#AF5F5F bg=#262626'
setw -g window-status-bell-style 'fg=#87875F,bold bg=#262626'

# Copy mode - dim selection
setw -g mode-style 'fg=#6C6C6C bg=#1C1C1C dim'

# Messages
set -g message-style 'fg=#87875F,bold bg=#262626'

# Clock
setw -g clock-mode-colour #AF5F5F