-- Monitor Configuration
-- Generated by nwg-displays; loads monitor settings at startup

local HOME = os.getenv("HOME")
local monitors_file = HOME .. "/.config/hypr/monitors.lua"

-- Load nwg-displays generated config if it exists
local f = io.open(monitors_file, "r")
if f then
  f:close()
  dofile(monitors_file)
else
  -- Fallback if nwg-displays config doesn't exist
  hl.monitor({
    output = "DP-2",
    mode = "2560x1440@144",
    position = "0x0",
    scale = 1,
  })
end
