# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-alacritty */

[colors.primary]
foreground = "#D8D8D9"
background = "#161616"
dim_foreground = "#858586"
bright_foreground = "#BEBFC0"

[colors.cursor]
text = "#161616"
cursor = "#979798"

[colors.vi_mode_cursor]
text = "#161616"
cursor = "#161616"

[colors.selection]
text = "#D8D8D9"
background = "#3D3D3D"

[colors.normal]
black   = "#3D3D3D"
red     = "#161616"
green   = "#404142"
yellow  = "#444445"
blue    = "#73353A"
magenta = "#6B6B6E"
cyan    = "#6B6B6E"
white   = "#BEBFC0"

[colors.bright]
black   = "#858586"
red     = "#1E1E1E"
green   = "#565658"
yellow  = "#5A5A5C"
blue    = "#99474D"
magenta = "#8F8F92"
cyan    = "#8F8F92"
white   = "#BEBFC0"

[colors.indexed_colors]
16  = "#161616"
17  = "#404142"
18  = "#444445"
19  = "#73353A"
20  = "#6B6B6E"
21  = "#6B6B6E"
