# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-tmux */

# Panes
set -g pane-border-style 'fg={{color8}}'
set -g pane-active-border-style 'fg={{color6}}'

# Status bar
set -g status-style 'fg={{color7}} bg={{background}}'
set -g status-left '#[fg={{color3}},bold][ #S ]#[default]    '
set -g status-right-style 'fg={{color6}} bg={{background}}'

# Window status
setw -g window-status-current-style 'fg={{color1}},bold bg={{background}}'
setw -g window-status-style 'fg={{color7}} bg={{background}}'
setw -g window-status-bell-style 'fg={{color3}},bold bg={{background}}'

# Copy mode
setw -g mode-style 'fg={{color1}} bg={{color0}} bold'

# Messages
set -g message-style 'fg={{color3}},bold bg={{background}}'

# Clock
setw -g clock-mode-colour {{color6}}
