set -g default-terminal "screen-256color"
set -g pane-border-style 'fg=#6b6b6b'
set -g pane-active-border-style 'fg=#75b5aa'
set -g status-justify left
set -g status-style 'fg=#d8d8d8'
set -g status-left '[ #S ]     '
set -g status-left-length 20
setw -g window-status-current-style 'fg=#f4bf75,bold bg=#17171A'
setw -g window-status-style 'fg=#B0B5B8 bg=#17171A'
setw -g window-status-bell-style 'fg=#191E2B,bold bg=#17171A'
setw -g mode-style 'fg=#d8d8d8,bg=#6b6b6b'
set -g message-style 'fg=#f4bf75,bg=#1a1a1a'
setw -g clock-mode-colour '#3a774d'
