services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    networks:
      services:
        ipv4_address: 10.0.0.5
    ports:
      - "3005:3005"
    environment:
      - ND_PORT=3005
    volumes:
      - /home/max/.local/navidrome/data:/data:z
      - /home/max/Music:/music:ro,z
    restart: unless-stopped
    security_opt:
      - label:disable    # Alternative: disable SELinux for this container only
    dns:
      - 10.0.0.1

networks:
  services:
    external: true
    name: services
