services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - /home/max/.local/navidrome/data:/data:z
      - /home/max/Music:/music:ro,z
    restart: unless-stopped
    security_opt:
      - label:disable    # Alternative: disable SELinux for this container only
