version: '3.8'

services:
  openspeedtest:
    image: openspeedtest/latest:latest
    container_name: openspeedtest
    networks:
      services:
        ipv4_address: 10.0.0.6
    ports:
      - "3006:3000"
      - "3007:3001"
    environment:
      - DOMAIN_NAME=openspeedtest.home
      - HTTP_PORT=3000
      - HTTPS_PORT=3001
    restart: unless-stopped
    dns:
      - 10.0.0.254

networks:
  services:
    external: true
    name: services
