dotfolder_path = "~/gitdot"
paths = ["~/.config/alacritty", "~/.config/hypr", "~/.config/nvim", "~/.p10k.zsh", "~/.config/lazydot.toml", "~/.icons", "~/.tmux.conf"]

[defaults]
on_duplicate = "overwritehome"
on_delink = "keep"
