version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    networks:
      - services
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    cap_drop:
      - ALL
    dns:
      - 10.0.0.1

networks:
  services:
    external: true
    name: services
